name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the code from the GitHub repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8 

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Terraform Plan for previewing changes
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform to create the S3 bucket
      - name: Terraform Apply
        run: terraform apply -auto-approve
